### ISSUE TITLE
Code for converting main_data to raw_data

### ISSUE THREAD

**Issue by Simons2017** [nikitacs16/Holl-E#1]
Hello, could you please provide code for converting main_data to raw_data? Thank you!

**Comment by nikitacs16** [comment]
Hi 
I have added the script now (convert_main_data_to_raw_data.py). Please let me know in case of further questions. As far as I remember some examples (~10 utterances) were also editted after the pre-processing for a particular occurence of a comma. 

Apologies for the delay. Feel free to email me if there is a delay to reply on github

**Comment by Simons2017** [comment]
Thank you for your code! Would you please provide evaluate.py for multi_reference_test.json?




------------------ 原始邮件 ------------------
发件人: "nikitacs16"<notifications@github.com>; 
发送时间: 2019年10月15日(星期二) 下午5:48
收件人: "nikitacs16/Holl-E"<Holl-E@noreply.github.com>; 
抄送: "1031091966"<1031091966@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [nikitacs16/Holl-E] Code for converting main_data to raw_data(#1)




Hi
I have added the script now (convert_main_data_to_raw_data.py). Please let me know in case of further questions. As far as I remember some examples (~10 utterances) were also editted after the pre-processing for a particular occurence of a comma.
 
Apologies for the delay. Feel free to email me if there is a delay to reply on github

**Comment by nikitacs16** [comment]
Uploaded in the metrics folder
