### ISSUE TITLE
Where are the tokenize_with_indices, find_first_numpy, space_remover and line_remover in convert_main_data_to_raw_data.py?

### ISSUE THREAD

**Issue by ce2020-ai** [nikitacs16/Holl-E#3]
I would like to know where tokenize_with_indices, find_first_numpy, space_remover and line_remover in convert_main_data_to_raw_data.py are?

**Comment by nikitacs16** [comment]
Hi 
They are not used in any of the functions in the rest of the file. Hence they have been commented with deprecated.

Apologies for the delay. Please communicate any further concerns to nikitamoghe29@gmail.com
